<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0;netstandard2.1;net8.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>A lightweight, asynchronous-compatible mutex for .NET, facilitating mutual exclusion across synchronous and asynchronous paradigms while incorporating cancellation semantics.</Description>
    <PackageTags>AsyncLock;Mutex;Locking;Async;Thread-Safe;Performance</PackageTags>
    <Copyright>Tedd Hansen</Copyright>
    <PackageProjectUrl>https://github.com/tedd/Tedd.AsyncLock</PackageProjectUrl>
    <RepositoryUrl>https://github.com/tedd/Tedd.AsyncLock.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>1.0.1</Version>
    <Authors>tedd</Authors>
    <Company>Tedd Hansen</Company>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="../../README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Tedd.ObjectPool" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net462' Or '$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
  </ItemGroup>

</Project>
